version: '3.8'
services:
  packetstream:
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 2
      resources:
        limits:
          cpus: "0.1"
          memory: '30M'
    image: packetstream/psclient:latest
    environment: 
      - CID=${CID}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    logging: 
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"